### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by boo82** [ngshiheng/six-percent#11]
I am getting the error below. Anything to check or what cause the issue below?

Traceback (most recent call last):
  File "main.py", line 14, in <module>
    user_data = json.load(u)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 32 column 1 (char 554)

**Comment by ksern94** [comment]
Can you show your user.json data? i'm guessing it's invalid json format

**Comment by boo82** [comment]
Does the json format accept special characters for the password?

Sent from Yahoo Mail on Android 
 
  On Mon, Oct 5, 2020 at 1:55 PM, ksern94<notifications@github.com> wrote:   


Can you show your user.json data? i'm guessing it's invalid json format

**Comment by ksern94** [comment]
Yes, special character is fine.
If you could show your users.json with id/pw omitted I can help you better.

Another guess, you might have a trailing comma in your last user object if you are copying from users.json.example directly.
