### ISSUE TITLE
Screenshot in your readme?

### ISSUE THREAD

**Issue by PySimpleGUI** [ngshiheng/six-percent#34]
I can't help but notice your application has a GUI, something that's pretty rare in the Python world.

Users love pictures has been my experience.  You can easily add one of your GUI.  There are instructions the Cookbook and in the  YouTube videos.

https://pysimplegui.readthedocs.io/en/latest/cookbook/#recipe-post-your-screen-shots-please

**Comment by ngshiheng** [comment]
Just did! Thanks for the suggestion!

**Comment by PySimpleGUI** [comment]
Ooo!  I like it!  Thank you!!

![image](https://user-images.githubusercontent.com/46163555/135709608-e1491a41-9fa6-4f2e-aa03-7247d771d1ba.png)

I like both the theme and that you've matches really well, aligned well.  Awesome!  You certainly have something worthy of showing off.
