### ISSUE TITLE
Login button element is not reachable

### ISSUE THREAD

**Issue by yeohcy7** [ngshiheng/six-percent#5]
Login button element is not reachable anymore after webpage design change with session.

Suggest change:
`
aTagsInLi = browser.find_elements_by_css_selector('li a')
for a in aTagsInLi:
if "https://www.myasnb.com.my/uh/uhlogin/index?id=" in a.get_attribute('href'):
            browser.get(a.get_attribute('href'))
            break
`

**Comment by yeohcy7** [comment]
Suggest change:
`
aTagsInLi = browser.find_elements_by_css_selector('li a')
    for a in aTagsInLi:
        if "https://www.myasnb.com.my/uh/uhlogin/index?id=" in a.get_attribute('href'):
            browser.get(a.get_attribute('href'))
            break
`

**Comment by ngshiheng** [comment]
@yeohcy7 I cant seem to reproduce the problem, can you submit a pull request so that I can take a look at it? :smile:
