### ISSUE TITLE
Unable to locate funds and additional declaration 

### ISSUE THREAD

**Issue by Polar8ear** [ngshiheng/six-percent#77]
I have just started using ASNB as of today (8 June 2022), I think there's some update in the past few days, maybe an UI update(?), that causes the program to stop working.

After comparing the locaters and the current classes of the funds, I think the work flow has changed as the previously invested funds and new funds are separated. I think it will needs some modification to current flow. Luckily the ui for both are identical and the purchase function is still working as expected.

Hereby I propose a possible workflow:
1. Get previously invested funds (Assuming that there's only ASMs)
1. For each fund:
    1. Click the first span in the div of the options
    1. Proceed with purchase action
    1. Click back button if no unit available
1. Get new funds by using xpath "//span[text()='ASM']" // IMHO I think name is pretty immune to change compared to classes
1. For each fund: // I think just check separately for ASM, ASM 2, ASM 3
    1. Click the first span in the div of the options
    1. Proceed with purchase action
    1. Click back button if no unit availabl

Moreover, there has been one more declaration about involvement in politics that needs to be clicked and confirmed as following:
![image](https://user-images.githubusercontent.com/64390556/172508228-40d723e4-e8e1-48f1-bad5-bc4bbc75c7c3.png)

**Comment by ngshiheng** [comment]
Just pushed the fix for this, this should work now
