### ISSUE TITLE
Problem with PEP (No) Confirmation and Return to Main Page. 

### ISSUE THREAD

**Issue by iSean97** [ngshiheng/six-percent#85]
Hey there @ngshiheng , wanted to ask is there anything I need to take note on on this Six-Percent app/Python Script?  
(1) Do I need to turn off PEP manually every time?  
(2) Also I'm encountering a bug where it fails to return to the main page of ASNB. 

Hope to hear from you soon. Great app. 
![image](https://user-images.githubusercontent.com/39750405/181664083-3890497f-6625-47f4-b067-7d5880dbaa36.png)

![image](https://user-images.githubusercontent.com/39750405/181663779-a8e13b85-f379-4552-bc9e-cf979476489c.png)

**Comment by ngshiheng** [comment]
Hey! I wasn't able to reproduce the 2 issues that you have encountered.
1. No, there shouldn't be able manual intervention needed. The only manual step is to make your own payment in case of a successful purchase attempt
2. Are all the 3 funds in your account considered as "initial investment" or "additional investment"?

Are there any errors written in the `sixpercent-errors.log` file?
What is the OS that you're running on? (You can check for Dxdiag)
What is the Chrome version that you're running on?
Is the app is running in Full Screen mode?

Sometimes if the Internet connection is slow, the HTML element may take a longer time to appear and then to be clicked, try to leave it as it is until the timeout occur

**Comment by iSean97** [comment]
**Are all the 3 funds in your account considered as "initial investment" or "additional investment"?**
- "additional investment"

**Are there any errors written in the sixpercent-errors.log file?**

I don't think it will generate any errors. Unless I used Ctrl + C to kill it. If it is stuck at PEP window:
![image](https://user-images.githubusercontent.com/39750405/181673631-4fc14ed0-becc-4cf0-9b9f-797b51483b12.png)
```

29-Jul-2022 11:00:15 ERROR Message: 
Stacktrace:
Backtrace:
```

If if manually clicked no the PEP, it will attempt to run ASM, but fails to return to main portfolio
```
29-Jul-2022 11:05:14 ERROR Unable to purchase fund now
29-Jul-2022 11:05:39 ERROR Message: 
Stacktrace:
Backtrace:
```

**What is the OS that you're running on? (You can check for Dxdiag)**
![image](https://user-images.githubusercontent.com/39750405/181673699-99d1db53-2a65-42dd-992a-98c2996af96f.png)

**What is the Chrome version that you're running on?**
![image](https://user-images.githubusercontent.com/39750405/181673839-9f856681-3e5c-47ee-82ae-bfb9489df6ef.png)

**Is the app is running in Full Screen mode?**
Shouldn't in the "F11" Full Screen mode in Chrome. 

May I know, what does this "pre-commit install" command do/how do I run it? 
I think this might be the issue? (I'm still quite new to this). 
![image](https://user-images.githubusercontent.com/39750405/181674853-727cef73-6034-4537-8517-1542a5fa0316.png)

**Comment by ngshiheng** [comment]
I've uploaded a new exe, can you check if that works for you? Can't remember the version that you're using has any outdated XPath 🤔 

About the pre-commit, you can ignore that, it's basically just a tool to ensure certain checks before someone creates a Git commit to the codebase

**Comment by iSean97** [comment]
Hello @ngshiheng, I've tried your new exe. 
Similar issues. 

It always get stuck at the Declaration of PEP page for me for both my laptops in Windows 10 and 11. 

Not sure what's the bug.

**Comment by ngshiheng** [comment]
@iSean97 I noticed that the language that you're using is English. You may need to use BM for this.

For example the PEP XPath checks for the word "Pengisytiharan PEP" (https://github.com/ngshiheng/six-percent/blob/master/src/locators.py#L28) instead of "Declaration of PEP"

I'm happy to review & accept a PR for this! Otherwise, I'll find time to update this maybe in the next couple of weeks
